id: IFDE2031D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T20:31:18+00:00'
last_modified: '2022-06-08T04:13:54.610823+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD76231
  title: མི་ཕམ་གསུང་འབུམ་ལས་གཞུང་འགྲེལ་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8213':
      image_group_id: I1PD84560
      title: Volume 1 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 324
      order: 1
      base_file: 8213.txt
    B954:
      image_group_id: I1PD84561
      title: Volume 2 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 230
      order: 2
      base_file: B954.txt
    C391:
      image_group_id: I1PD84562
      title: Volume 3 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 358
      order: 3
      base_file: C391.txt
    '1737':
      image_group_id: I1PD84563
      title: Volume 4 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 484
      order: 4
      base_file: 1737.txt
    414A:
      image_group_id: I1PD84564
      title: Volume 5 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 295
      order: 5
      base_file: 414A.txt
    '8979':
      image_group_id: I1PD84565
      title: Volume 6 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 430
      order: 6
      base_file: 8979.txt
    025A:
      image_group_id: I1PD84566
      title: Volume 7 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 390
      order: 7
      base_file: 025A.txt
    2B77:
      image_group_id: I1PD84567
      title: Volume 8 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 346
      order: 8
      base_file: 2B77.txt
    62BB:
      image_group_id: I1PD84568
      title: Volume 9 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 242
      order: 9
      base_file: 62BB.txt
    2D9B:
      image_group_id: I1PD84569
      title: Volume 10 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 290
      order: 10
      base_file: 2D9B.txt
    F141:
      image_group_id: I1PD84570
      title: Volume 11 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 484
      order: 11
      base_file: F141.txt
    C479:
      image_group_id: I1PD84571
      title: Volume 12 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 314
      order: 12
      base_file: C479.txt
    DAB5:
      image_group_id: I1PD84572
      title: Volume 13 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 260
      order: 13
      base_file: DAB5.txt
    '6054':
      image_group_id: I1PD84573
      title: Volume 14 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 370
      order: 14
      base_file: 6054.txt
    F5FF:
      image_group_id: I1PD84574
      title: Volume 15 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 306
      order: 15
      base_file: F5FF.txt
    EE78:
      image_group_id: I1PD84575
      title: Volume 16 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 220
      order: 16
      base_file: EE78.txt
    BFB7:
      image_group_id: I1PD84576
      title: Volume 17 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 328
      order: 17
      base_file: BFB7.txt
    720A:
      image_group_id: I1PD84577
      title: Volume 18 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 330
      order: 18
      base_file: 720A.txt
    33D6:
      image_group_id: I1PD84578
      title: Volume 19 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 328
      order: 19
      base_file: 33D6.txt
    FF7D:
      image_group_id: I1PD84579
      title: Volume 20 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 316
      order: 20
      base_file: FF7D.txt
    '6505':
      image_group_id: I1PD84580
      title: Volume 21 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 426
      order: 21
      base_file: 6505.txt
    0854:
      image_group_id: I1PD84581
      title: Volume 22 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 472
      order: 22
      base_file: 0854.txt
    69EA:
      image_group_id: I1PD84582
      title: Volume 23 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 262
      order: 23
      base_file: 69EA.txt
    0A93:
      image_group_id: I1PD84583
      title: Volume 24 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 302
      order: 24
      base_file: 0A93.txt
    35E2:
      image_group_id: I1PD84584
      title: Volume 25 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 370
      order: 25
      base_file: 35E2.txt
    C00B:
      image_group_id: I1PD84585
      title: Volume 26 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 340
      order: 26
      base_file: C00B.txt
    '1798':
      image_group_id: I1PD84586
      title: Volume 27 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 266
      order: 27
      base_file: 1798.txt
    7ECB:
      image_group_id: I1PD84587
      title: Volume 28 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 264
      order: 28
      base_file: 7ECB.txt
    D66D:
      image_group_id: I1PD84588
      title: Volume 29 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 468
      order: 29
      base_file: D66D.txt
    C154:
      image_group_id: I1PD84589
      title: Volume 30 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 392
      order: 30
      base_file: C154.txt
    37F9:
      image_group_id: I1PD84590
      title: Volume 31 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 180
      order: 31
      base_file: 37F9.txt
    7CA1:
      image_group_id: I1PD84591
      title: Volume 32 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 366
      order: 32
      base_file: 7CA1.txt
    DBB0:
      image_group_id: I1PD84592
      title: Volume 33 of mi pham gsung 'bum las gzhung 'grel skor
      total_pages: 298
      order: 33
      base_file: DBB0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
